package consts

// 常量定义
const (
	GVA_DATA_PATH          = "data"
	INITIAL_LOCK_FILE_NAME = "initial.lock"

	// JWT 相关常量
	JWT_EXPIRES_TIME_DEFAULT = "7d"
	JWT_BUFFER_TIME_DEFAULT  = "1d"
	JWT_ISSUER_DEFAULT       = "gin-vue-admin"

	// zap 相关常量
	ZAP_LEVEL_DEFAULT          = "info"
	ZAP_PREFIX_DEFAULT         = "[github.com/flipped-aurora/gin-vue-admin/server]"
	ZAP_FORMAT_DEFAULT         = "console"
	ZAP_DIRECTOR_DEFAULT       = "logs"
	ZAP_ENCODE_LEVEL_DEFAULT   = "LowercaseLevelEncoder"
	ZAP_STACKTRACE_KEY_DEFAULT = "stacktrace"
	ZAP_SHOW_LINE_DEFAULT      = true
	ZAP_LOG_IN_CONSOLE_DEFAULT = true
	ZAP_RETENTION_DAY_DEFAULT  = -1

	// redis 相关常量
	REIDS_NAME_DEFAULT        = "default"
	REDIS_ADDR_DEFAULT        = "localhost:6379"
	REDIS_PASSWORD_DEFAULT    = ""
	REDIS_DB_DEFAULT          = 0
	REDIS_USE_CLUSTER_DEFAULT = false

	// mongo 相关常量
	MONGO_COLL_DEFAULT               = ""
	MONGO_OPTIONS_DEFAULT            = ""
	MONGO_DATABASE_DEFAULT           = ""
	MONGO_USERNAME_DEFAULT           = ""
	MONGO_PASSWORD_DEFAULT           = ""
	MONGO_AUTH_SOURCE_DEFAULT        = ""
	MONGO_MIN_POOL_SIZE_DEFAULT      = uint64(0)
	MONGO_MAX_POOL_SIZE_DEFAULT      = uint64(100)
	MONGO_SOCKET_TIMEOUT_MS_DEFAULT  = int64(0)
	MONGO_CONNECT_TIMEOUT_MS_DEFAULT = int64(0)
	MONGO_IS_ZAP_DEFAULT             = false
	MONGO_HOSTS_DEFAULT              = ""

	// email 相关常量
	EMAIL_TO_DEFAULT            = ""
	EMAIL_FROM_DEFAULT          = ""
	EMAIL_HOST_DEFAULT          = ""
	EMAIL_SECRET_DEFAULT        = ""
	EMAIL_NICKNAME_DEFAULT      = ""
	EMAIL_PORT_DEFAULT          = 0
	EMAIL_IS_SSL_DEFAULT        = false
	EMAIL_IS_LOGIN_AUTH_DEFAULT = false

	// system 相关常量
	SYSTEM_DB_TYPE_DEFAULT              = "pgsql"
	SYSTEM_OSS_TYPE_DEFAULT             = "local"
	SYSTEM_ROUTER_PREFIX_DEFAULT        = ""
	SYSTEM_ADDR_DEFAULT                 = 8888
	SYSTEM_LIMIT_COUNT_IP_DEFAULT       = 15000
	SYSTEM_LIMIT_TIME_IP_DEFAULT        = 3600
	SYSTEM_USE_MULTIPOINT_DEFAULT       = false
	SYSTEM_USE_REDIS_DEFAULT            = false
	SYSTEM_USE_MONGO_DEFAULT            = false
	SYSTEM_USE_STRICT_AUTH_DEFAULT      = false
	SYSTEM_DISABLE_AUTO_MIGRATE_DEFAULT = false

	// captcha 相关常量
	CAPTCHA_KEY_LONG_DEFAULT             = 6
	CAPTCHA_IMG_WIDTH_DEFAULT            = 240
	CAPTCHA_IMG_HEIGHT_DEFAULT           = 80
	CAPTCHA_OPEN_CAPTCHA_DEFAULT         = 0
	CAPTCHA_OPEN_CAPTCHA_TIMEOUT_DEFAULT = 3600

	// autocode 相关常量
	AUTOCODE_WEB_DEFAULT     = ""
	AUTOCODE_ROOT_DEFAULT    = ""
	AUTOCODE_SERVER_DEFAULT  = ""
	AUTOCODE_MODULE_DEFAULT  = ""
	AUTOCODE_AI_PATH_DEFAULT = ""

	// 通用数据库字段默认值
	DB_PREFIX_DEFAULT         = ""
	DB_PATH_DEFAULT           = ""
	DB_PORT_DEFAULT           = ""
	DB_CONFIG_DEFAULT         = ""
	DB_NAME_DEFAULT           = ""
	DB_USERNAME_DEFAULT       = ""
	DB_PASSWORD_DEFAULT       = ""
	DB_ENGINE_DEFAULT         = "InnoDB"
	DB_LOG_MODE_DEFAULT       = ""
	DB_MAX_IDLE_CONNS_DEFAULT = 10
	DB_MAX_OPEN_CONNS_DEFAULT = 100
	DB_SINGULAR_DEFAULT       = false
	DB_LOG_ZAP_DEFAULT        = false

	// local 相关常量
	LOCAL_PATH_DEFAULT       = "files"
	LOCAL_STORE_PATH_DEFAULT = "files"

	// qiniu 相关常量
	QINIU_ZONE_DEFAULT            = ""
	QINIU_BUCKET_DEFAULT          = ""
	QINIU_IMG_PATH_DEFAULT        = ""
	QINIU_ACCESS_KEY_DEFAULT      = ""
	QINIU_SECRET_KEY_DEFAULT      = ""
	QINIU_USE_HTTPS_DEFAULT       = false
	QINIU_USE_CDN_DOMAINS_DEFAULT = false

	// aliyun-oss 相关常量
	ALIYUN_OSS_ENDPOINT_DEFAULT          = ""
	ALIYUN_OSS_ACCESS_KEY_ID_DEFAULT     = ""
	ALIYUN_OSS_ACCESS_KEY_SECRET_DEFAULT = ""
	ALIYUN_OSS_BUCKET_NAME_DEFAULT       = ""
	ALIYUN_OSS_BUCKET_URL_DEFAULT        = ""
	ALIYUN_OSS_BASE_PATH_DEFAULT         = ""

	// hua-wei-obs 相关常量
	HUAWEI_OBS_PATH_DEFAULT       = ""
	HUAWEI_OBS_BUCKET_DEFAULT     = ""
	HUAWEI_OBS_ENDPOINT_DEFAULT   = ""
	HUAWEI_OBS_ACCESS_KEY_DEFAULT = ""
	HUAWEI_OBS_SECRET_KEY_DEFAULT = ""

	// tencent-cos 相关常量
	TENCENT_COS_BUCKET_DEFAULT      = ""
	TENCENT_COS_REGION_DEFAULT      = ""
	TENCENT_COS_SECRET_ID_DEFAULT   = ""
	TENCENT_COS_SECRET_KEY_DEFAULT  = ""
	TENCENT_COS_BASE_URL_DEFAULT    = ""
	TENCENT_COS_PATH_PREFIX_DEFAULT = ""

	// aws-s3 相关常量
	AWS_S3_BUCKET_DEFAULT           = ""
	AWS_S3_REGION_DEFAULT           = ""
	AWS_S3_ENDPOINT_DEFAULT         = ""
	AWS_S3_SECRET_ID_DEFAULT        = ""
	AWS_S3_SECRET_KEY_DEFAULT       = ""
	AWS_S3_BASE_URL_DEFAULT         = ""
	AWS_S3_PATH_PREFIX_DEFAULT      = ""
	AWS_S3_FORCE_PATH_STYLE_DEFAULT = false
	AWS_S3_DISABLE_SSL_DEFAULT      = false

	// cloudflare-r2 相关常量
	CLOUDFLARE_R2_BUCKET_DEFAULT            = ""
	CLOUDFLARE_R2_BASE_URL_DEFAULT          = ""
	CLOUDFLARE_R2_PATH_DEFAULT              = ""
	CLOUDFLARE_R2_ACCOUNT_ID_DEFAULT        = ""
	CLOUDFLARE_R2_ACCESS_KEY_ID_DEFAULT     = ""
	CLOUDFLARE_R2_SECRET_ACCESS_KEY_DEFAULT = ""

	// minio 相关常量
	MINIO_ENDPOINT_DEFAULT          = ""
	MINIO_ACCESS_KEY_ID_DEFAULT     = ""
	MINIO_ACCESS_KEY_SECRET_DEFAULT = ""
	MINIO_BUCKET_NAME_DEFAULT       = ""
	MINIO_USE_SSL_DEFAULT           = false
	MINIO_BASE_PATH_DEFAULT         = ""
	MINIO_BUCKET_URL_DEFAULT        = ""

	// excel 相关常量
	EXCEL_DIR_DEFAULT = "./excel"

	// disk 相关常量
	DISK_MOUNT_POINTS_DEFAULT = ""

	// cors 相关常量
	CORS_MODE_DEFAULT = ""

	// mcp 相关常量
	MCP_NAME_DEFAULT         = "GVA_MCP"
	MCP_VERSION_DEFAULT      = "v1.0.0"
	MCP_SSE_PATH_DEFAULT     = "/see"
	MCP_MESSAGE_PATH_DEFAULT = "/message"
	MCP_URL_PREFIX_DEFAULT   = ""
	MCP_ADDR_DEFAULT         = 8889
	MCP_SEPARATE_DEFAULT     = false
)

// 环境变量定义 ， 设置环境变量请在前面添加 GVA_ 前缀， 例如 GVA_DATA_PATH
const (
	ENV_GVA_DATA_PATH = "DATA_PATH"    // 数据目录
	ENV_AUTO_INITIAL  = "AUTO_INITIAL" // 是否自动转跳到初始化界面
	ENV_HAS_INITIAL   = "HAS_INITIAL"  // 是否已经初始化
	ENV_GIN_MODE      = "GIN_MODE"     // gin 模式，默认为 debug 模式，可选值有 debug、release、test

	// JWT 相关环境变量
	ENV_JWT_SIGNING_KEY  = "JWT_SIGNING"
	ENV_JWT_EXPIRES_TIME = "JWT_EXPIRES_TIME"
	ENV_JWT_BUFFER_TIME  = "JWT_BUFFER_TIME"
	ENV_JWT_ISSUER       = "JWT_ISSUER"

	// zap 相关环境变量
	ENV_ZAP_LEVEL          = "ZAP_LEVEL"
	ENV_ZAP_PREFIX         = "ZAP_PREFIX"
	ENV_ZAP_FORMAT         = "ZAP_FORMAT"
	ENV_ZAP_DIRECTOR       = "ZAP_DIRECTOR"
	ENV_ZAP_ENCODE_LEVEL   = "ZAP_ENCODE_LEVEL"
	ENV_ZAP_STACKTRACE_KEY = "ZAP_STACKTRACE_KEY"
	ENV_ZAP_SHOW_LINE      = "ZAP_SHOW_LINE"
	ENV_ZAP_LOG_IN_CONSOLE = "ZAP_LOG_IN_CONSOLE"
	ENV_ZAP_RETENTION_DAY  = "ZAP_RETENTION_DAY"

	// redis 相关环境变量
	ENV_REDIS_NAME          = "REDIS_NAME"
	ENV_REDIS_ADDR          = "REDIS_ADDR"
	ENV_REDIS_PASSWORD      = "REDIS_PASSWORD"
	ENV_REDIS_DB            = "REDIS_DB"
	ENV_REDIS_USE_CLUSTER   = "REDIS_USE_CLUSTER"
	ENV_REDIS_CLUSTER_ADDRS = "REDIS_CLUSTER_ADDRS"

	// mongo 相关环境变量
	ENV_MONGO_COLL               = "MONGO_COLL"
	ENV_MONGO_OPTIONS            = "MONGO_OPTIONS"
	ENV_MONGO_DATABASE           = "MONGO_DATABASE"
	ENV_MONGO_USERNAME           = "MONGO_USERNAME"
	ENV_MONGO_PASSWORD           = "MONGO_PASSWORD"
	ENV_MONGO_AUTH_SOURCE        = "MONGO_AUTH_SOURCE"
	ENV_MONGO_MIN_POOL_SIZE      = "MONGO_MIN_POOL_SIZE"
	ENV_MONGO_MAX_POOL_SIZE      = "MONGO_MAX_POOL_SIZE"
	ENV_MONGO_SOCKET_TIMEOUT_MS  = "MONGO_SOCKET_TIMEOUT_MS"
	ENV_MONGO_CONNECT_TIMEOUT_MS = "MONGO_CONNECT_TIMEOUT_MS"
	ENV_MONGO_IS_ZAP             = "MONGO_IS_ZAP"
	ENV_MONGO_HOSTS              = "MONGO_HOSTS"

	// email 相关环境变量
	ENV_EMAIL_TO            = "EMAIL_TO"
	ENV_EMAIL_FROM          = "EMAIL_FROM"
	ENV_EMAIL_HOST          = "EMAIL_HOST"
	ENV_EMAIL_SECRET        = "EMAIL_SECRET"
	ENV_EMAIL_NICKNAME      = "EMAIL_NICKNAME"
	ENV_EMAIL_PORT          = "EMAIL_PORT"
	ENV_EMAIL_IS_SSL        = "EMAIL_IS_SSL"
	ENV_EMAIL_IS_LOGIN_AUTH = "EMAIL_IS_LOGIN_AUTH"

	// system 相关环境变量
	ENV_SYSTEM_DB_TYPE              = "SYSTEM_DB_TYPE"
	ENV_SYSTEM_OSS_TYPE             = "SYSTEM_OSS_TYPE"
	ENV_SYSTEM_ROUTER_PREFIX        = "SYSTEM_ROUTER_PREFIX"
	ENV_SYSTEM_ADDR                 = "SYSTEM_ADDR"
	ENV_SYSTEM_LIMIT_COUNT_IP       = "SYSTEM_LIMIT_COUNT_IP"
	ENV_SYSTEM_LIMIT_TIME_IP        = "SYSTEM_LIMIT_TIME_IP"
	ENV_SYSTEM_USE_MULTIPOINT       = "SYSTEM_USE_MULTIPOINT"
	ENV_SYSTEM_USE_REDIS            = "SYSTEM_USE_REDIS"
	ENV_SYSTEM_USE_MONGO            = "SYSTEM_USE_MONGO"
	ENV_SYSTEM_USE_STRICT_AUTH      = "SYSTEM_USE_STRICT_AUTH"
	ENV_SYSTEM_DISABLE_AUTO_MIGRATE = "SYSTEM_DISABLE_AUTO_MIGRATE"

	// captcha 相关环境变量
	ENV_CAPTCHA_KEY_LONG             = "CAPTCHA_KEY_LONG"
	ENV_CAPTCHA_IMG_WIDTH            = "CAPTCHA_IMG_WIDTH"
	ENV_CAPTCHA_IMG_HEIGHT           = "CAPTCHA_IMG_HEIGHT"
	ENV_CAPTCHA_OPEN_CAPTCHA         = "CAPTCHA_OPEN_CAPTCHA"
	ENV_CAPTCHA_OPEN_CAPTCHA_TIMEOUT = "CAPTCHA_OPEN_CAPTCHA_TIMEOUT"

	// autocode 相关环境变量
	ENV_AUTOCODE_WEB     = "AUTOCODE_WEB"
	ENV_AUTOCODE_ROOT    = "AUTOCODE_ROOT"
	ENV_AUTOCODE_SERVER  = "AUTOCODE_SERVER"
	ENV_AUTOCODE_MODULE  = "AUTOCODE_MODULE"
	ENV_AUTOCODE_AI_PATH = "AUTOCODE_AI_PATH"

	// mysql 相关环境变量
	ENV_MYSQL_PREFIX         = "MYSQL_PREFIX"
	ENV_MYSQL_PATH           = "MYSQL_PATH"
	ENV_MYSQL_PORT           = "MYSQL_PORT"
	ENV_MYSQL_CONFIG         = "MYSQL_CONFIG"
	ENV_MYSQL_DB_NAME        = "MYSQL_DB_NAME"
	ENV_MYSQL_USERNAME       = "MYSQL_USERNAME"
	ENV_MYSQL_PASSWORD       = "MYSQL_PASSWORD"
	ENV_MYSQL_ENGINE         = "MYSQL_ENGINE"
	ENV_MYSQL_LOG_MODE       = "MYSQL_LOG_MODE"
	ENV_MYSQL_MAX_IDLE_CONNS = "MYSQL_MAX_IDLE_CONNS"
	ENV_MYSQL_MAX_OPEN_CONNS = "MYSQL_MAX_OPEN_CONNS"
	ENV_MYSQL_SINGULAR       = "MYSQL_SINGULAR"
	ENV_MYSQL_LOG_ZAP        = "MYSQL_LOG_ZAP"

	// mssql 相关环境变量
	ENV_MSSQL_PREFIX         = "MSSQL_PREFIX"
	ENV_MSSQL_PATH           = "MSSQL_PATH"
	ENV_MSSQL_PORT           = "MSSQL_PORT"
	ENV_MSSQL_CONFIG         = "MSSQL_CONFIG"
	ENV_MSSQL_DB_NAME        = "MSSQL_DB_NAME"
	ENV_MSSQL_USERNAME       = "MSSQL_USERNAME"
	ENV_MSSQL_PASSWORD       = "MSSQL_PASSWORD"
	ENV_MSSQL_ENGINE         = "MSSQL_ENGINE"
	ENV_MSSQL_LOG_MODE       = "MSSQL_LOG_MODE"
	ENV_MSSQL_MAX_IDLE_CONNS = "MSSQL_MAX_IDLE_CONNS"
	ENV_MSSQL_MAX_OPEN_CONNS = "MSSQL_MAX_OPEN_CONNS"
	ENV_MSSQL_SINGULAR       = "MSSQL_SINGULAR"
	ENV_MSSQL_LOG_ZAP        = "MSSQL_LOG_ZAP"

	// pgsql 相关环境变量
	ENV_PGSQL_PREFIX         = "PGSQL_PREFIX"
	ENV_PGSQL_PATH           = "PGSQL_PATH"
	ENV_PGSQL_PORT           = "PGSQL_PORT"
	ENV_PGSQL_CONFIG         = "PGSQL_CONFIG"
	ENV_PGSQL_DB_NAME        = "PGSQL_DB_NAME"
	ENV_PGSQL_USERNAME       = "PGSQL_USERNAME"
	ENV_PGSQL_PASSWORD       = "PGSQL_PASSWORD"
	ENV_PGSQL_ENGINE         = "PGSQL_ENGINE"
	ENV_PGSQL_LOG_MODE       = "PGSQL_LOG_MODE"
	ENV_PGSQL_MAX_IDLE_CONNS = "PGSQL_MAX_IDLE_CONNS"
	ENV_PGSQL_MAX_OPEN_CONNS = "PGSQL_MAX_OPEN_CONNS"
	ENV_PGSQL_SINGULAR       = "PGSQL_SINGULAR"
	ENV_PGSQL_LOG_ZAP        = "PGSQL_LOG_ZAP"

	// oracle 相关环境变量
	ENV_ORACLE_PREFIX         = "ORACLE_PREFIX"
	ENV_ORACLE_PATH           = "ORACLE_PATH"
	ENV_ORACLE_PORT           = "ORACLE_PORT"
	ENV_ORACLE_CONFIG         = "ORACLE_CONFIG"
	ENV_ORACLE_DB_NAME        = "ORACLE_DB_NAME"
	ENV_ORACLE_USERNAME       = "ORACLE_USERNAME"
	ENV_ORACLE_PASSWORD       = "ORACLE_PASSWORD"
	ENV_ORACLE_ENGINE         = "ORACLE_ENGINE"
	ENV_ORACLE_LOG_MODE       = "ORACLE_LOG_MODE"
	ENV_ORACLE_MAX_IDLE_CONNS = "ORACLE_MAX_IDLE_CONNS"
	ENV_ORACLE_MAX_OPEN_CONNS = "ORACLE_MAX_OPEN_CONNS"
	ENV_ORACLE_SINGULAR       = "ORACLE_SINGULAR"
	ENV_ORACLE_LOG_ZAP        = "ORACLE_LOG_ZAP"

	// sqlite 相关环境变量
	ENV_SQLITE_PREFIX         = "SQLITE_PREFIX"
	ENV_SQLITE_PATH           = "SQLITE_PATH"
	ENV_SQLITE_PORT           = "SQLITE_PORT"
	ENV_SQLITE_CONFIG         = "SQLITE_CONFIG"
	ENV_SQLITE_DB_NAME        = "SQLITE_DB_NAME"
	ENV_SQLITE_USERNAME       = "SQLITE_USERNAME"
	ENV_SQLITE_PASSWORD       = "SQLITE_PASSWORD"
	ENV_SQLITE_ENGINE         = "SQLITE_ENGINE"
	ENV_SQLITE_LOG_MODE       = "SQLITE_LOG_MODE"
	ENV_SQLITE_MAX_IDLE_CONNS = "SQLITE_MAX_IDLE_CONNS"
	ENV_SQLITE_MAX_OPEN_CONNS = "SQLITE_MAX_OPEN_CONNS"
	ENV_SQLITE_SINGULAR       = "SQLITE_SINGULAR"
	ENV_SQLITE_LOG_ZAP        = "SQLITE_LOG_ZAP"

	// local 相关环境变量
	ENV_LOCAL_PATH       = "LOCAL_PATH"
	ENV_LOCAL_STORE_PATH = "LOCAL_STORE_PATH"

	// qiniu 相关环境变量
	ENV_QINIU_ZONE            = "QINIU_ZONE"
	ENV_QINIU_BUCKET          = "QINIU_BUCKET"
	ENV_QINIU_IMG_PATH        = "QINIU_IMG_PATH"
	ENV_QINIU_ACCESS_KEY      = "QINIU_ACCESS_KEY"
	ENV_QINIU_SECRET_KEY      = "QINIU_SECRET_KEY"
	ENV_QINIU_USE_HTTPS       = "QINIU_USE_HTTPS"
	ENV_QINIU_USE_CDN_DOMAINS = "QINIU_USE_CDN_DOMAINS"

	// aliyun-oss 相关环境变量
	ENV_ALIYUN_OSS_ENDPOINT          = "ALIYUN_OSS_ENDPOINT"
	ENV_ALIYUN_OSS_ACCESS_KEY_ID     = "ALIYUN_OSS_ACCESS_KEY_ID"
	ENV_ALIYUN_OSS_ACCESS_KEY_SECRET = "ALIYUN_OSS_ACCESS_KEY_SECRET"
	ENV_ALIYUN_OSS_BUCKET_NAME       = "ALIYUN_OSS_BUCKET_NAME"
	ENV_ALIYUN_OSS_BUCKET_URL        = "ALIYUN_OSS_BUCKET_URL"
	ENV_ALIYUN_OSS_BASE_PATH         = "ALIYUN_OSS_BASE_PATH"

	// hua-wei-obs 相关环境变量
	ENV_HUAWEI_OBS_PATH       = "HUAWEI_OBS_PATH"
	ENV_HUAWEI_OBS_BUCKET     = "HUAWEI_OBS_BUCKET"
	ENV_HUAWEI_OBS_ENDPOINT   = "HUAWEI_OBS_ENDPOINT"
	ENV_HUAWEI_OBS_ACCESS_KEY = "HUAWEI_OBS_ACCESS_KEY"
	ENV_HUAWEI_OBS_SECRET_KEY = "HUAWEI_OBS_SECRET_KEY"

	// tencent-cos 相关环境变量
	ENV_TENCENT_COS_BUCKET      = "TENCENT_COS_BUCKET"
	ENV_TENCENT_COS_REGION      = "TENCENT_COS_REGION"
	ENV_TENCENT_COS_SECRET_ID   = "TENCENT_COS_SECRET_ID"
	ENV_TENCENT_COS_SECRET_KEY  = "TENCENT_COS_SECRET_KEY"
	ENV_TENCENT_COS_BASE_URL    = "TENCENT_COS_BASE_URL"
	ENV_TENCENT_COS_PATH_PREFIX = "TENCENT_COS_PATH_PREFIX"

	// aws-s3 相关环境变量
	ENV_AWS_S3_BUCKET           = "AWS_S3_BUCKET"
	ENV_AWS_S3_REGION           = "AWS_S3_REGION"
	ENV_AWS_S3_ENDPOINT         = "AWS_S3_ENDPOINT"
	ENV_AWS_S3_SECRET_ID        = "AWS_S3_SECRET_ID"
	ENV_AWS_S3_SECRET_KEY       = "AWS_S3_SECRET_KEY"
	ENV_AWS_S3_BASE_URL         = "AWS_S3_BASE_URL"
	ENV_AWS_S3_PATH_PREFIX      = "AWS_S3_PATH_PREFIX"
	ENV_AWS_S3_FORCE_PATH_STYLE = "AWS_S3_FORCE_PATH_STYLE"
	ENV_AWS_S3_DISABLE_SSL      = "AWS_S3_DISABLE_SSL"

	// cloudflare-r2 相关环境变量
	ENV_CLOUDFLARE_R2_BUCKET            = "CLOUDFLARE_R2_BUCKET"
	ENV_CLOUDFLARE_R2_BASE_URL          = "CLOUDFLARE_R2_BASE_URL"
	ENV_CLOUDFLARE_R2_PATH              = "CLOUDFLARE_R2_PATH"
	ENV_CLOUDFLARE_R2_ACCOUNT_ID        = "CLOUDFLARE_R2_ACCOUNT_ID"
	ENV_CLOUDFLARE_R2_ACCESS_KEY_ID     = "CLOUDFLARE_R2_ACCESS_KEY_ID"
	ENV_CLOUDFLARE_R2_SECRET_ACCESS_KEY = "CLOUDFLARE_R2_SECRET_ACCESS_KEY"

	// minio 相关环境变量
	ENV_MINIO_ENDPOINT          = "MINIO_ENDPOINT"
	ENV_MINIO_ACCESS_KEY_ID     = "MINIO_ACCESS_KEY_ID"
	ENV_MINIO_ACCESS_KEY_SECRET = "MINIO_ACCESS_KEY_SECRET"
	ENV_MINIO_BUCKET_NAME       = "MINIO_BUCKET_NAME"
	ENV_MINIO_USE_SSL           = "MINIO_USE_SSL"
	ENV_MINIO_BASE_PATH         = "MINIO_BASE_PATH"
	ENV_MINIO_BUCKET_URL        = "MINIO_BUCKET_URL"

	// excel 相关环境变量
	ENV_EXCEL_DIR = "EXCEL_DIR"

	// disk 相关环境变量
	ENV_DISK_MOUNT_POINTS = "DISK_MOUNT_POINTS"

	// cors 相关环境变量
	ENV_CORS_MODE = "CORS_MODE"

	// mcp 相关环境变量
	ENV_MCP_NAME         = "MCP_NAME"
	ENV_MCP_VERSION      = "MCP_VERSION"
	ENV_MCP_SSE_PATH     = "MCP_SSE_PATH"
	ENV_MCP_MESSAGE_PATH = "MCP_MESSAGE_PATH"
	ENV_MCP_URL_PREFIX   = "MCP_URL_PREFIX"
	ENV_MCP_ADDR         = "MCP_ADDR"
	ENV_MCP_SEPARATE     = "MCP_SEPARATE"
)
